DROP TABLE IF EXISTS technician;
DROP TABLE IF EXISTS report;

CREATE TABLE technician (
  id SERIAL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE report (
  id SERIAL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  MULF TEXT NOT NULL,
  area TEXT NOT NULL,
  takenby INTEGER
);

CREATE TABLE region (
  id SERIAL,
  name TEXT NOT NULL

);

CREATE TABLE area (
  id SERIAL,
  name TEXT NOT NULL,
  region_id INTEGER
);
