DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS report;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE report (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  MULF TEXT NOT NULL,
  area TEXT NOT NULL,
  takenby INTEGER
);
